spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: checkout-shopping
#Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: usershopping
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shoppingCheckout
    password: us3rSh0p
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: 'true'
#        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/realms/ajromero/protocol/openid-connect/certs
          issuer-uri: http://localhost:8082/realms/ajromero
server:
    port: '9000'
    servlet:
      context-path: /api
logging:
  level:
    org:
      springframework: INFO
    root: WARN
    com:
      ajromero: DEBUG


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers
    enabled-by-default: 'false'
  endpoint:
    health:
      enabled: 'true'
    metrics:
      enabled: 'true'
    loggers:
      enabled: 'true'


